gateway="ngtw.cytech.pro:443"
token="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3OWEwM2UxMy1mMjNkLTQ0ODctOTM1Ni1lMzc1Njg0N2NlNjUiLCJuYW1lIjoiZ2l0aHViIiwiZXhwIjoxNzEwMjI3ODA2fQ.fnY-Yxjvi1vJU6S0VtdHQMendmZx_IbgEOAyhZaggNw"
